export const STORAGE_KEYS = {
  CONFIG: 'spm_config',
  VENUES: 'spm_venues',
  TABLE_SPECS: 'spm_tableSpecs',
  FIXTURE_TYPES: 'spm_fixtureTypes',
  GUIDELINES: 'spm_guidelines',
  TEMPLATES: 'spm_templates',
  USERS: 'spm_users',
  LINEN_COLORS: 'spm_linenColors',
  SAVED_LAYOUTS: 'spm_savedLayouts',

  UI_PREFS: 'spm_ui_prefs',
  ADMIN_LAST_TAB: 'spm_admin_last_tab',

  CHAIR_SPECS_PRIMARY: 'spm_chair_specs',
  CHAIR_SPECS_LEGACY: 'spm_chairSpecs',
  WALL_STYLES: 'spm_wall_styles',
  SPACING_SETTINGS: 'spm_spacing_settings',
  ALIGNMENT_SETTINGS: 'spm_alignment_settings',
  INDOOR_FEATURE_TEMPLATES: 'spm_indoor_feature_templates',
  OUTDOOR_FEATURE_TEMPLATES: 'spm_outdoor_feature_templates',

  DECOR_ITEMS: 'spm_decor_catalog',
  DECOR_CATEGORIES: 'spm_decor_categories',
  DECOR_ARRANGEMENTS: 'spm_decor_arrangements',
  DECOR_PACKAGES: 'spm_decor_packages',

  EVENT_ROLES: 'spm_event_roles',
  EVENT_QUESTIONS: 'spm_event_questions',
  RBAC_ROLES: 'spm_rbac_roles',
  RBAC_GROUPS: 'spm_rbac_groups',
  RBAC_AUDIT: 'spm_rbac_audit',
  EVENT_ANSWERS: 'spm_event_answers',
  EVENT_SUBMISSIONS: 'spm_event_submissions_v1',

  DIRECT_MESSAGES: 'spm_direct_messages_v1',

  PORTAL_CONFIG: 'spm_portal_config',
  PORTAL_AUTH: 'spm_portal_auth',
  PORTAL_GUESTS: 'spm_portal_guests',
  RSVP_SUBMISSIONS: 'spm_rsvp_submissions',

  COUPLE_EVENTS: 'spm_couple_events',
  COUPLE_SESSION: 'spm_couple_session',
  COUPLE_ANSWERS: 'spm_couple_answers',
  COUPLE_SUBMISSIONS: 'spm_couple_submissions',
  COUPLE_MESSAGES: 'spm_couple_messages',
  COUPLE_CHAT_READ: 'spm_couple_chat_read',
  COUPLE_GUESTS: 'spm_couple_guests',
  COUPLE_PORTAL_CONFIGS: 'spm_couple_portal_configs',
  COUPLE_CHECKLISTS: 'spm_couple_checklists',
  COUPLE_VENDORS: 'spm_couple_vendors',
  COUPLE_SETUP_TASKS: 'spm_couple_setup_tasks',
  WEDDING_PACKAGES: 'spm_wedding_packages',
  PACKAGE_ADDONS: 'spm_package_addons',
  COUPLE_GUEST_EVENTS: 'spm_couple_guest_events',
  VENUE_CALENDAR_EVENTS: 'spm_venue_calendar_events',
  VENUE_MAP_CONFIGS: 'spm_venue_map_configs',
  VENUE_RULES: 'spm_venue_rules',
  VENUE_WEATHER: 'spm_venue_weather',

  STAFF_TASKS: 'spm_staff_tasks',
  STAFF_AREAS: 'spm_staff_areas',
  STAFF_SHIFTS: 'spm_staff_shifts',
  VENDORS: 'spm_vendors',
  VENDOR_PAYMENTS: 'spm_vendor_payments',
  TIMELINES: 'spm_timelines',

  SESSION_V2: 'spm_session_v2',
  SESSION_LEGACY: 'spm_session',
  REMEMBERED_USER: 'spm_remembered_user',
  PASSWORD_RESET_CODE: 'spm_reset_code',
  WELCOME_HIDDEN: 'spm_welcome_hidden',

  LAYOUT_EDIT_SESSIONS: 'spm_layout_edit_sessions',
  BACKUP_ROLLBACK: 'spm_backup_rollback_latest',
  RECOVERY_SNAPSHOT: 'spm_recovery_emergency_snapshot',
} as const;