export const STORAGE_VERSIONS = {
  CONFIG: 2,
  SAVED_LAYOUTS: 3,
  LAYOUT_EDIT_SESSIONS: 1,
  DIRECT_MESSAGES: 1,
  EVENT_SUBMISSIONS: 1,
  PORTAL_CONFIG: 2,
  PORTAL_GUESTS: 1,
  RSVP_SUBMISSIONS: 1,
  COUPLE_EVENTS: 1,
  COUPLE_ANSWERS: 1,
  COUPLE_SUBMISSIONS: 1,
  COUPLE_MESSAGES: 1,
} as const;